spring.application.name=school-control
spring.profiles.active=populated
grade.MAX.SCORE=100

# Configuración de la base de datos H2
# http://localhost:8080/h2-console
spring.datasource.url=jdbc:h2:file:./data/school
spring.datasource.username=pollitos_school
spring.datasource.password=password
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop



