spring.application.name=school-control
spring.profiles.active=default
grade.MAX.SCORE=100
logging.level.org.springframework=INFO

# H2 database configuration: http://localhost:8080/h2-console
spring.datasource.url=jdbc:h2:file:./data/school
spring.datasource.username=pollitos_school
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop





